# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # gradle(task: "clean assembleRelease")
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta', aab: "../build/app/outputs/bundle/release/app-release.aab")
    slack(message: 'Successfully distributed a new beta build')
    # crashlytics
  
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean assembleRelease"
    )
  
  end

  lane :distribute  do
    # build_android_app(task: "bundle")
    sh "flutter build apk --release"
   
    # build_android_app is a built-in fastlane action.
    release = firebase_app_distribution(
        app: "1:334203700014:android:64d8c85e0269f15bfff0bf",
        service_credentials_file: "deploy_firebase_gallery-app-d2d7c-3e0b117a0f00.json",
        # testers: "luke.nguyen.goldenowl@gmail.com",
        groups:"tester",
        release_notes: "new features to test out!",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end
