name: Build & upload to Firebase App Distribution 

on: 
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:


  build:

    name: Building and distributing app
    runs-on: ubuntu-latest

    env: 
      working-directory: /home/runner/work/training_keith_dart_challenge/training_keith_dart_challenge/gallery_app

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'



      - name: Add secret
        working-directory: ${{env.working-directory}}
        run: echo ${{secrets.FIREBASE_KEY}} | base64 -d > deploy_firebase_gallery-app-d2d7c-3e0b117a0f00.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
          build-root-directory: ${{env.working-directory}}
          cache-disabled: true
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Test
        working-directory: ${{env.working-directory}}
        run: |
          echo
          pwd

          echo
          ls

          echo
          echo ls root
          ls ../

          
          echo
          echo ls root2
          ls -R ../../
        
      - name: Distribute firebase
        working-directory: ${{env.working-directory}}
        run: fastlane distribute
     
